language: bash

# Doc
# - Travis Job Lifecycle : https://docs.travis-ci.com/user/job-lifecycle/

matrix:
  include:
    - name: "Linux Debug"
      os: linux
      dist: bionic
      env:
        - BUILD_NAME="linux-macos"
        - MODE=Debug

    - name: "MacOS Debug"
      os: osx
      osx_image: xcode9.4
      env:
        - BUILD_NAME="linux-macos"
        - MODE=Debug
        - CC=gcc-9
        - CXX=g++-9
      addons:
        homebrew:
          # update: true
          packages:
            - gcc@9 # ou llvm@10

    - name: "Windows Debug"
      os: windows
      env:
        - BUILD_NAME="windows"
        - MODE=Debug

install:
  - ${TRAVIS_BUILD_DIR}/.travis-ci/${BUILD_NAME}/install.sh

before_script:
  - ${TRAVIS_BUILD_DIR}/.travis-ci/${BUILD_NAME}/before_script.sh

script:
  - ${TRAVIS_BUILD_DIR}/.travis-ci/${BUILD_NAME}/build.sh
