#ifndef CPP_TRAINING_SOLUTIONS_NEWTON_VECTORIAL_COMMON_HPP
#define CPP_TRAINING_SOLUTIONS_NEWTON_VECTORIAL_COMMON_HPP

using Real = double;

namespace VectorNewton {}

#endif // CPP_TRAINING_SOLUTIONS_NEWTON_VECTORIAL_COMMON_HPP
